### ISSUE TITLE
concept_t in polymorphic ducks needs a virtual destructor

### ISSUE THREAD

**Issue by juanchopanza** [mropert/mropert.github.io#5]
Small, but important detail: your `drawable` type uses a `unique_ptr<concept_t>`, but your `concept_t` does not have a virtual destructor. I think in the Sean Parent talk that inspired this post, he uses a `shared_ptr<concept_t>`, which captures the derived type on construction and uses it in the deleter, and does not require a virtual destructor.

**Comment by mropert** [comment]
Thanks for your comment but as far as I can see the destructor in the `concept_t` is indeed virtual in the examples I've shown in the article.

**Comment by juanchopanza** [comment]
You're absolutely right. My eyes seem to have fooled me. Sorry for the noise.
